---
- name: Nexus Setup
  hosts: nexus01
  become: yes
  tasks:
  - name: setup openjdk
    shell: |
      apt install 
  
  - name: setup openjdk
    shell: |
      apt install 

  - name:  
    shell: |
      mkdir -p /opt/nexus/
      mkdir -p /tmp/nexus/
      cd /tmp/nexus/
      NEXUSURL="https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
      wget $NEXUSURL -O nexus.tar.gz
      sleep 10
      EXTOUT=`tar xzvf nexus.tar.gz`
      NEXUSDIR=`echo $EXTOUT | cut -d '/' -f1`
      sleep 5
      rm -rf /tmp/nexus/nexus.tar.gz
      cp -r /tmp/nexus/* /opt/nexus/
      sleep 5
      useradd nexus
      chown -R nexus.nexus /opt/nexus
    register: output

  - debug: var=output.stdout_lines

  - name: Systemd unit file setup
    shell: |
      cat <<EOT>> /etc/systemd/system/nexus.service
      [Unit]                                                                          
      Description=nexus service                                                       
      After=network.target                                                            
                                                                  
      [Service]                                                                       
      Type=forking                                                                    
      LimitNOFILE=65536                                                               
      ExecStart=/opt/nexus/$NEXUSDIR/bin/nexus start                                  
      ExecStop=/opt/nexus/$NEXUSDIR/bin/nexus stop                                    
      User=nexus                                                                      
      Restart=on-abort                                                                
                                                                  
      [Install]                                                                       
      WantedBy=multi-user.target                                                      

      EOT
    register: output

  - debug: var=output.stdout_lines
  
  - name: Systemctl setup
    shell: |
      echo 'run_as_user="nexus"' > /opt/nexus/$NEXUSDIR/bin/nexus.rc
      systemctl daemon-reload
      systemctl start nexus
      systemctl enable nexus
    register: output
  
  - debug: var=output.stdout_lines

  
    